# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_pausa', 'En Pausa'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gastado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
