# Generated by Django 4.2.11 on 2026-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('operaciones', 'Operaciones'), ('diseno_mecanico', 'Diseno Mecanico'), ('hardware_design', 'Hardware Design'), ('ensamble', 'Ensamble'), ('programacion_plc', 'Programacion PLC'), ('manufactura', 'Manufactura'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='Colaborador', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('pm', 'Operaciones'), ('staff', 'Colaborador')], default='staff', max_length=20),
        ),
    ]
