# Generated by Django 4.2.11 on 2026-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_department_alter_user_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('operaciones', 'Operaciones'), ('business_intelligence', 'Business Intelligence'), ('diseno_mecanico', 'Diseno Mecanico'), ('hardware_design', 'Hardware Design'), ('ensamble', 'Ensamble'), ('programacion_plc', 'Programacion PLC'), ('manufactura', 'Manufactura'), ('otro', 'Otro')], max_length=50),
        ),
    ]
