# Generated by Django 4.2.11 on 2026-02-11 19:59

from django.db import migrations, models


def sync_roles_by_department(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    role_by_department = {
        'business_intelligence': 'admin',
        'finanzas': 'finance',
        'operaciones': 'pm',
    }

    for user in User.objects.all().iterator():
        expected_role = role_by_department.get(user.department, 'staff')
        if user.role != expected_role:
            user.role = expected_role
            user.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('finance', 'Finanzas'), ('pm', 'Operaciones'), ('staff', 'Colaborador')], default='staff', max_length=20),
        ),
        migrations.RunPython(sync_roles_by_department, migrations.RunPython.noop),
    ]
