[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"

[build.env]
NPM_CONFIG_PRODUCTION = "false"
NIXPACKS_NODE_VERSION = "20"

[build.commands]
install = "npm ci"
build = "npm run build"
