"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

raw_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
allowed_hosts = [host.strip() for host in raw_allowed_hosts.split(',') if host.strip()]
railway_public = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
railway_private = os.environ.get('RAILWAY_PRIVATE_DOMAIN')
railway_env = os.environ.get('RAILWAY_ENVIRONMENT')
for host in (railway_public, railway_private):
    if host:
        allowed_hosts.append(host)
# Fallback to allow all hosts to avoid healthcheck 400s on Railway.
ALLOWED_HOSTS = list(dict.fromkeys(allowed_hosts + ['*']))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'proyectos',
    'viaticos',
    'viajes',
    'flotilla',
    'conciliacion',
    'amex',
    'catalogos',
    'recuperacion',
    'dispersion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('POSTGRES_DB', 'finanzas'),
        'USER': os.environ.get('POSTGRES_USER', 'finanzas'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'finanzas'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOW_CREDENTIALS = True

def parse_csv_env(name: str, default: str) -> list[str]:
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def normalize_origin(origin: str | None) -> str:
    value = (origin or '').strip()
    if not value:
        return ''
    if '://' not in value:
        value = f'https://{value}'
    parsed = urlparse(value)
    if not parsed.scheme or not parsed.netloc:
        return ''
    return f'{parsed.scheme.lower()}://{parsed.netloc.lower()}'


frontend_url = normalize_origin(os.environ.get('FRONTEND_URL'))
cors_origins = [
    normalize_origin(origin)
    for origin in parse_csv_env(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    )
]
csrf_origins = [
    normalize_origin(origin)
    for origin in parse_csv_env(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    )
]
if frontend_url:
    cors_origins.append(frontend_url)

# Keep CSRF and CORS origins aligned for session-based auth from browser apps.
csrf_origins.extend(cors_origins)

# Railway frontend domains change per project/environment; allow wildcard for CSRF/CORS.
railway_wildcard_origin = 'https://*.up.railway.app'
csrf_origins.append(railway_wildcard_origin)

CORS_ALLOWED_ORIGINS = [origin for origin in dict.fromkeys(cors_origins) if origin]
CSRF_TRUSTED_ORIGINS = [origin for origin in dict.fromkeys(csrf_origins) if origin]
CORS_ALLOWED_ORIGIN_REGEXES = parse_csv_env(
    'CORS_ALLOWED_ORIGIN_REGEXES',
    r'^https://.*\.up\.railway\.app$',
)

IS_PRODUCTION = (not DEBUG) or bool(railway_public or railway_private or railway_env)
COOKIE_SAMESITE = os.environ.get('DJANGO_COOKIE_SAMESITE', 'None' if IS_PRODUCTION else 'Lax')
SESSION_COOKIE_SAMESITE = COOKIE_SAMESITE
CSRF_COOKIE_SAMESITE = COOKIE_SAMESITE
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', 'true' if IS_PRODUCTION else 'false').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_SECURE_COOKIES', 'true' if IS_PRODUCTION else 'false').lower() == 'true'

def normalize_cookie_domain(raw_value: str | None) -> str | None:
    value = (raw_value or '').strip()
    if not value:
        return None
    if '://' in value:
        parsed = urlparse(value)
        value = parsed.hostname or ''
    value = value.strip().lower()
    if not value:
        return None
    stripped = value.lstrip('.')
    # `up.railway.app` is a public suffix, so browsers reject domain cookies for it.
    if stripped == 'up.railway.app':
        return None
    return f'.{stripped}'


resolved_cookie_domain = normalize_cookie_domain(os.environ.get('DJANGO_COOKIE_DOMAIN'))
if resolved_cookie_domain:
    SESSION_COOKIE_DOMAIN = resolved_cookie_domain
    CSRF_COOKIE_DOMAIN = resolved_cookie_domain

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
