# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaticos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1-15', '1-15'), ('16-30', '16-30')], max_length=10)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('facturas', models.IntegerField(default=0)),
                ('consumos', models.IntegerField(default=0)),
                ('matched', models.IntegerField(default=0)),
                ('discrepancias', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('revisada', 'Revisada')], default='en_proceso', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=120)),
                ('uuid', models.CharField(max_length=120)),
                ('rfc', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago', models.CharField(max_length=120)),
                ('metodo_pago', models.CharField(max_length=120)),
                ('conceptos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada'), ('conciliada', 'Conciliada')], default='pendiente', max_length=20)),
                ('archivo_xml', models.FileField(blank=True, null=True, upload_to='conciliacion/xml/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='conciliacion/pdf/')),
                ('validacion_cfdi', models.JSONField(blank=True, default=dict)),
                ('match_consumo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
                ('viatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaticos.viatico')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comercio', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(max_length=120)),
                ('factura_pdf_name', models.CharField(blank=True, max_length=200)),
                ('factura_xml_name', models.CharField(blank=True, max_length=200)),
                ('factura_notas', models.TextField(blank=True)),
                ('matched', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to=settings.AUTH_USER_MODEL)),
                ('viatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaticos.viatico')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consumo_sin_factura', 'Consumo sin factura'), ('factura_sin_consumo', 'Factura sin consumo'), ('monto_diferente', 'Monto diferente'), ('articulo_personal', 'Articulo personal'), ('propina_excedida', 'Propina excedida'), ('duplicado', 'Duplicado')], max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('gravedad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='conciliacion.conciliacion')),
                ('consumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.consumo')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.factura')),
            ],
        ),
    ]
