DEFAULT_GS_ACTIVITIES = [
    {
        'id': 1,
        'label': 'Support',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 2,
        'label': 'Commissioning',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 3,
        'label': 'Instalation',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 4,
        'label': 'Assembly Build',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 5,
        'label': 'Levantamiento',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': False,
        'note': '',
    },
    {
        'id': 6,
        'label': 'Lunch',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': False,
        'note': '',
    },
    {
        'id': 7,
        'label': 'Viaticos TE',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 8,
        'label': 'Visa',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
    {
        'id': 9,
        'label': 'Otro',
        'account': '5450',
        'code': 'N/A',
        'category': 'travel',
        'proyecto_requerido': True,
        'note': '',
    },
]

DEFAULT_CUENTAS_CONTABLES = [
    {
        'codigo': '5450',
        'nombre': 'Travel Expenses/Meals',
        'descripcion': 'Gastos de viaje y alimentos relacionados a proyectos especificos',
        'categoria': 'Viaticos',
        'proyecto_requerido': True,
        'keywords': [
            'hotel',
            'hospedaje',
            'lodging',
            'accommodation',
            'vuelo',
            'flight',
            'avion',
            'airline',
            'meal',
            'comida',
            'restaurant',
            'restaurante',
            'uber',
            'taxi',
            'transporte',
            'transportation',
            'rental',
            'renta',
            'gasoline',
            'gasolina',
            'pemex',
            'shell',
            'bp',
        ],
        'activa': True,
    },
    {
        'codigo': '6090',
        'nombre': 'Office Supplies',
        'descripcion': 'Papeleria y suministros de oficina',
        'categoria': 'Administrativo',
        'proyecto_requerido': False,
        'keywords': [
            'office',
            'depot',
            'papeleria',
            'supplies',
            'staples',
            'pens',
            'paper',
            'printer',
            'toner',
            'cartridge',
            'folder',
            'binder',
            'notebook',
            'escritorio',
            'silla',
            'muebles',
        ],
        'activa': True,
    },
    {
        'codigo': '6200',
        'nombre': 'Expense - Non Project',
        'descripcion': 'Gastos no relacionados a proyectos especificos',
        'categoria': 'General',
        'proyecto_requerido': False,
        'keywords': [],
        'activa': True,
    },
]

DEFAULT_DEPARTMENTS = [
    {'value': 'finanzas', 'label': 'Finanzas'},
    {'value': 'operaciones', 'label': 'Operaciones'},
    {'value': 'business_intelligence', 'label': 'Business Intelligence'},
    {'value': 'diseno_mecanico', 'label': 'Diseno Mecanico'},
    {'value': 'hardware_design', 'label': 'Hardware Design'},
    {'value': 'ensamble', 'label': 'Ensamble'},
    {'value': 'programacion_plc', 'label': 'Programacion PLC'},
    {'value': 'manufactura', 'label': 'Manufactura'},
    {'value': 'otro', 'label': 'Otro'},
]

DEFAULT_USER_CATEGORIES = [
    {'value': 'gerente', 'label': 'Gerente'},
    {'value': 'operador', 'label': 'Operador'},
]

PROTECTED_DEPARTMENT_VALUES = {'business_intelligence', 'finanzas', 'operaciones'}
GS_ACTIVITY_OTHER_ID = 9
