# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_activity_id', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('origen', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('destino_pais', models.CharField(choices=[('Mexico', 'Mexico'), ('USA', 'USA'), ('Otro', 'Otro')], default='Mexico', max_length=20)),
                ('tipo_viatico', models.CharField(choices=[('efectifintech', 'Efectivo/Fintech'), ('amex', 'AMEX'), ('mixto', 'Mixto')], default='efectifintech', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_dispersado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_gastado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('saldo_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('dispersado', 'Dispersado'), ('en_viaje', 'En Viaje'), ('viaje_finalizado', 'Viaje Finalizado'), ('en_recuperacion', 'En Recuperacion'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('comentarios', models.TextField(blank=True)),
                ('vehiculo_asignado', models.CharField(blank=True, max_length=120)),
                ('gasto_fuente', models.CharField(blank=True, choices=[('manual', 'Manual'), ('efectifintech', 'Efectifintech')], max_length=20)),
                ('efectifintech_id', models.CharField(blank=True, max_length=120)),
                ('efectifintech_status', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], max_length=20)),
                ('efectifintech_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('dias_sin_recuperar', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaticos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViaticoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('xml', 'XML'), ('ticket', 'Ticket')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='viaticos/documentos/')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='viaticos.viatico')),
            ],
        ),
    ]
