# Generated by Django 4.2.11 on 2026-03-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='General', max_length=120)),
                ('proyecto_requerido', models.BooleanField(default=False)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='GSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('account', models.CharField(default='5450', max_length=20)),
                ('code', models.CharField(default='N/A', max_length=20)),
                ('category', models.CharField(choices=[('job', 'Job/Proyecto'), ('travel', 'Motivo de Viaje'), ('facility', 'Facility'), ('employee', 'Employee'), ('office', 'Office'), ('vehicle', 'Vehicle')], default='travel', max_length=20)),
                ('proyecto_requerido', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
