# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaticos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('anio', models.IntegerField()),
                ('placas', models.CharField(max_length=20, unique=True)),
                ('numero_serie', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(max_length=80)),
                ('seguro_compania', models.CharField(blank=True, max_length=120)),
                ('seguro_poliza', models.CharField(blank=True, max_length=120)),
                ('seguro_vigencia', models.DateField(blank=True, null=True)),
                ('mantenimiento_ultimo_servicio', models.DateField(blank=True, null=True)),
                ('mantenimiento_km_ultimo', models.IntegerField(blank=True, null=True)),
                ('mantenimiento_proximo_servicio', models.DateField(blank=True, null=True)),
                ('mantenimiento_km_proximo', models.IntegerField(blank=True, null=True)),
                ('km_actual', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_taller', 'En Taller'), ('baja', 'Baja')], default='disponible', max_length=20)),
                ('foto', models.FileField(blank=True, null=True, upload_to='flotilla/vehiculos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('proposito', models.CharField(choices=[('operaciones', 'Operaciones'), ('visita', 'Visita'), ('viaje', 'Viaje')], max_length=20)),
                ('km_inicial', models.IntegerField(default=0)),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('foto_odometro_inicial', models.FileField(blank=True, null=True, upload_to='flotilla/odometro/')),
                ('foto_odometro_final', models.FileField(blank=True, null=True, upload_to='flotilla/odometro/')),
                ('checklist_recepcion', models.JSONField(blank=True, default=dict)),
                ('checklist_entrega', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('asignado', 'Asignado'), ('activo', 'Activo'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20)),
                ('incidentes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='flotilla.vehicle')),
                ('viatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viaticos.viatico')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasolina', 'Gasolina'), ('mantenimiento', 'Mantenimiento'), ('seguro', 'Seguro'), ('verificacion', 'Verificacion'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('factura_id', models.CharField(blank=True, max_length=120)),
                ('odometro', models.IntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.vehicleassignment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='flotilla.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('otro', 'Otro')], max_length=20)),
                ('tipo_alerta', models.CharField(choices=[('servicio', 'Servicio'), ('seguro', 'Seguro'), ('verificacion', 'Verificacion'), ('placas', 'Placas'), ('reparacion', 'Reparacion')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.DateField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proveedor_sugerido', models.CharField(blank=True, max_length=120)),
                ('atendido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='flotilla.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('correctivo', 'Correctivo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimiento', to='flotilla.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CargaGasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_litro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odometro', models.IntegerField()),
                ('estacion', models.CharField(max_length=120)),
                ('factura_id', models.CharField(blank=True, max_length=120)),
                ('eficiencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.vehicleassignment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_gasolina', to='flotilla.vehicle')),
            ],
        ),
    ]
