# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viaticos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('moneda', models.CharField(choices=[('MXN', 'MXN'), ('USD', 'USD')], default='MXN', max_length=3)),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('confirmado', models.BooleanField(default=False)),
                ('dispersado_por', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('viatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispersiones', to='viaticos.viatico')),
            ],
        ),
    ]
