# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('necesita_avion', models.BooleanField(default=False)),
                ('necesita_camion', models.BooleanField(default=False)),
                ('necesita_hotel', models.BooleanField(default=False)),
                ('detalles_avion', models.TextField(blank=True)),
                ('detalles_camion', models.TextField(blank=True)),
                ('detalles_hotel', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('status_avion', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('gestionando', 'Gestionando'), ('confirmado', 'Confirmado')], max_length=20)),
                ('status_camion', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('gestionando', 'Gestionando'), ('confirmado', 'Confirmado')], max_length=20)),
                ('status_hotel', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('gestionando', 'Gestionando'), ('confirmado', 'Confirmado')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmaciones_avion', models.JSONField(blank=True, default=list)),
                ('confirmaciones_camion', models.JSONField(blank=True, default=list)),
                ('confirmaciones_hotel', models.JSONField(blank=True, default=list)),
                ('atendido_por', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_viaje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
