# Generated by Django 4.2.11 on 2026-01-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0001_initial'),
        ('conciliacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaAMEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10)),
                ('card_holder', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAMEX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=10)),
                ('card_holder', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('comercio', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('categoria', models.CharField(max_length=120)),
                ('cuenta_contable', models.CharField(max_length=20)),
                ('gs_activity_id', models.IntegerField(blank=True, null=True)),
                ('pais_comercio', models.CharField(max_length=120)),
                ('factura_pdf_name', models.CharField(blank=True, max_length=200)),
                ('factura_xml_name', models.CharField(blank=True, max_length=200)),
                ('factura_notas', models.TextField(blank=True)),
                ('matched', models.BooleanField(default=False)),
                ('autorizado', models.BooleanField(default=False)),
                ('duplicado', models.BooleanField(default=False)),
                ('clasificacion_auto', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.factura')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
