from datetime import date

from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.test import APITestCase

from .models import CargaGasolina, MaintenanceRecord, Vehicle, VehicleAlert, VehicleAssignment, VehicleExpense


User = get_user_model()


class FlotillaCreateTests(APITestCase):
    def setUp(self):
        self.staff_user = User.objects.create_user(
            email='flotilla.staff@na.scio-automation.com',
            full_name='Flotilla Staff',
            department='manufactura',
            position='Colaborador',
            password='SecurePass123',
        )
        self.admin_user = User.objects.create_user(
            email='flotilla.admin@na.scio-automation.com',
            full_name='Flotilla Admin',
            department='finanzas',
            position='Administrador',
            password='SecurePass123',
        )
        self.vehicle = Vehicle.objects.create(
            marca='Toyota',
            modelo='Corolla',
            anio=2023,
            placas='QA-123',
            numero_serie='SERIEQA1234567890',
            color='Blanco',
            km_actual=15000,
            status=Vehicle.Status.DISPONIBLE,
        )

    def test_staff_assignment_without_user_is_assigned_to_request_user(self):
        self.client.force_authenticate(user=self.staff_user)
        response = self.client.post(
            '/api/flotilla/asignaciones/',
            {
                'vehicle': self.vehicle.id,
                'motivo': 'Prueba de asignacion',
                'proposito': 'operaciones',
                'fecha_inicio': '2026-02-01',
                'km_inicial': 15000,
            },
            format='json',
        )
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['user'], self.staff_user.id)

    def test_staff_assignment_user_spoof_is_overridden(self):
        self.client.force_authenticate(user=self.staff_user)
        response = self.client.post(
            '/api/flotilla/asignaciones/',
            {
                'vehicle': self.vehicle.id,
                'user': self.admin_user.id,
                'motivo': 'Prueba de asignacion',
                'proposito': 'operaciones',
                'fecha_inicio': '2026-02-01',
                'km_inicial': 15000,
            },
            format='json',
        )
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['user'], self.staff_user.id)

    def test_admin_gasoline_load_without_user_defaults_to_request_user(self):
        self.client.force_authenticate(user=self.admin_user)
        response = self.client.post(
            '/api/flotilla/gasolina/',
            {
                'vehicle': self.vehicle.id,
                'fecha': '2026-02-01',
                'litros': '35.00',
                'precio_litro': '23.50',
                'total': '822.50',
                'odometro': 15100,
                'estacion': 'PEMEX QA',
            },
            format='json',
        )
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['user'], self.admin_user.id)
        self.assertEqual(VehicleExpense.objects.filter(tipo=VehicleExpense.Tipo.GASOLINA).count(), 1)

    def test_vehicle_alerts_are_autogenerated_from_vehicle_data(self):
        self.vehicle.seguro_vigencia = date(2027, 12, 31)
        self.vehicle.save(update_fields=['seguro_vigencia'])

        response = self.client.get('/api/flotilla/alertas/')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertGreaterEqual(len(response.data), 2)
        self.assertTrue(VehicleAlert.objects.filter(vehicle=self.vehicle, tipo_alerta='servicio').exists())

    def test_gasoline_endpoint_backfills_from_expenses(self):
        self.client.force_authenticate(user=self.admin_user)
        assignment = VehicleAssignment.objects.create(
            vehicle=self.vehicle,
            user=self.admin_user,
            motivo='Visita de servicio',
            proposito='operaciones',
            fecha_inicio='2026-02-10',
            km_inicial=15000,
            km_final=15300,
            status='completado',
        )
        VehicleExpense.objects.create(
            vehicle=self.vehicle,
            assignment=assignment,
            tipo=VehicleExpense.Tipo.GASOLINA,
            fecha='2026-02-10',
            monto='920.00',
            descripcion='Carga de 40 litros',
            proveedor='PEMEX QA',
        )

        response = self.client.get('/api/flotilla/gasolina/')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(CargaGasolina.objects.count(), 1)
        self.assertEqual(response.data[0]['odometro'], 15300)

    def test_maintenance_endpoint_backfills_from_expenses(self):
        self.client.force_authenticate(user=self.admin_user)
        VehicleExpense.objects.create(
            vehicle=self.vehicle,
            tipo=VehicleExpense.Tipo.MANTENIMIENTO,
            fecha='2026-02-12',
            monto='1500.00',
            descripcion='Cambio de aceite y filtros',
            odometro=15400,
            proveedor='Taller QA',
        )

        response = self.client.get('/api/flotilla/mantenimiento/')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        self.assertEqual(MaintenanceRecord.objects.count(), 1)
